### ISSUE TITLE
Error: object ‘as.tbl_cube’ is not exported by 'namespace:dplyr'

### ISSUE THREAD

**Issue by aasberg** [LAPKB/Pmetrics#15] opened 2020-06-02 08:45 UTC
Trying to install Pmetrics on an iMac using: 
devtools::install_github("LAPKB/Pmetrics")

and then gets this error:
Error: object ‘as.tbl_cube’ is not exported by 'namespace:dplyr'

Worked fine on my MacBook Pro.....

**Comment by mhovd** [comment] 2020-06-02 09:21
I get this error as well, on both Mac and Windows. This seems to be due to `dplyr 1.0.0` [changelog](https://dplyr.tidyverse.org/news/index.html), where `tbl_cube` was removed to a different package. Installing `dplyr 0.8.2` might be a workaround.

EDIT: Manually installing `dplyr 0.8.2` and then getting the newest version of `PMetrics` from GitHub seems to work for now.

**Comment by aasberg** [comment] 2020-06-02 10:04
The workaround fixed the installation problem.

**Comment by mnneely** [comment] 2020-06-09 20:29
This was caused by the package author moving as.tbl_cube function from dplyr to a new package called cubelyr.  The problem is fixed in Pmetrics v1.9.6.

**Closed as completed by mnneely** 2020-06-09 20:29 UTC
