### ISSUE TITLE
makeValid restrictions?

### ISSUE THREAD

**Issue by aasberg** [LAPKB/Pmetrics#36] opened 2020-12-19 12:51 UTC
Are there any restrictions using makeValid? I have a model with a drug dosed both once and twice daily and also use the steady state function; addl=-1. I only specify observations up to 12 hours after dose (all patients have this). Get this error:

*****************************
Use, for example, SIMparse(“full1.txt”) to extract simulator output for analysis or plotting.
Error in { : 
  task 1 failed - "scan() expected 'a real', got '0.1409088+309'"
******************************

**Comment by Siel** [comment] 2021-01-04 20:57
I'm not sure what is the cause of the error but this error:
Error in { :
task 1 failed - "scan() expected 'a real', got '0.1409088+309'"

can be fixed by opening the file and appending an E after the '+' symbol. It's a pretty manual fix but it works at the end.

**Comment by mnneely** [comment] 2021-01-04 21:26
Did you include limits in the makeValid function? Looks like one of your simulated outputs was vast and caused an error.

Sent from my iPhone

On Dec 19, 2020, at 4:51 AM, Anders Asberg <notifications@github.com> wrote:

﻿

Are there any restrictions using makeValid? I have a model with a drug dosed both once and twice daily and also use the steady state function; addl=-1. I only specify observations up to 12 hours after dose (all patients have this). Get this error:

________________________________

Use, for example, SIMparse(“full1.txt”) to extract simulator output for analysis or plotting.
Error in { :
task 1 failed - "scan() expected 'a real', got '0.1409088+309'"

________________________________

**Comment by aasberg** [comment] 2021-01-04 23:12
Thanks Julian and Michael! I forgot to set limits and when I rerun with, it worked fine! You are super!

**Comment by Siel** [comment] 2021-01-05 00:06
I'm goin to close the issue then :)

**Closed as completed by Siel** 2021-01-05 00:06 UTC
